"""Initial plants revision

Revision ID: 4509ab451014
Revises: 
Create Date: 2024-02-13 19:43:52.333487

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4509ab451014"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("default",)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
