"""plants model

Revision ID: 74b04b06752d
Revises: 4509ab451014
Create Date: 2024-02-15 16:18:56.018542

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74b04b06752d"
down_revision: Union[str, None] = "4509ab451014"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plant",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "title_tsv",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            sa.Computed("to_tsvector('english', \"title\")", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "description_tsv",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            sa.Computed("to_tsvector('english', \"description\")", persisted=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_plants_description_tsv",
        "plant",
        ["description_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_plants_title_tsv",
        "plant",
        ["title_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "plant_file",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("file_key", sa.String(length=64), nullable=True),
        sa.Column("file_location", sa.String(), nullable=True),
        sa.Column("plant_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plant_file")
    op.drop_index("idx_plants_title_tsv", table_name="plant", postgresql_using="gin")
    op.drop_index(
        "idx_plants_description_tsv", table_name="plant", postgresql_using="gin"
    )
    op.drop_table("plant")
    # ### end Alembic commands ###
